version: '2'

services:

  build-aws-elasticache-client-7.2:
    build:
        context: .
        dockerfile: Dockerfile

    volumes:
      - ${PWD}/build-7.2:/build

    command:
      /bin/bash /tmp/build.sh
      